name: Genshin Daily Check-in

on:
  schedule:
    # Run daily at 8:00 AM UTC (adjust timezone as needed)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  daily-checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run daily check-in
      env:
        ACT_ID: ${{ secrets.ACT_ID }}
        COOKIE: ${{ secrets.COOKIE }}
        API_URL: ${{ secrets.API_URL }}
      run: python checkin/daily.py
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: checkin-logs
        path: log.txt
        retention-days: 30

    - name: Upload logs to Gist
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: python checkin/upload_to_gist.py